service: cupon

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  punto2:
    handler: bin/punto2
    events:
      - http:
          path: punto2
          method: get

